server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
#          uri: http://localhost:8081 # ???? ??, http://localhost:8000/user ? ???? http://localhost:8081 ? ???
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/** # ?? gateway ??? /service1/**? ???? ?? eureka-client-1? ?????? ??
#            - Method=GET
          filters:
            - AddRequestHeader=token, 123456
            - AddResponseHeader=authenticated, yes

        - id: order-service
#          uri: http://localhost:8082 # ??? ? ??, http://localhost:8000/order ? ???? http://localhost:8082 ? ???
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/** # ?? gateway ??? /service2/**? ???? ?? eureka-client-2? ?????? ??
#            - Method=GET0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
