server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: eureka-client-1
#          uri: http://localhost:8081 # ???? ??, http://localhost:8000/user ? ???? http://localhost:8081 ? ???
          uri: lb://EUREKA-CLIENT-1
          predicates:
            - Path=/service1/** # ?? gateway ??? /service1/**? ???? ?? eureka-client-1? ?????? ??
            - Method=GET
          filters:
            - AddRequestHeader=token, 123456
            - AddResponseHeader=authenticated, yes

        - id: eureka-client-2
#          uri: http://localhost:8082 # ??? ? ??, http://localhost:8000/order ? ???? http://localhost:8082 ? ???
          uri: lb://EUREKA-CLIENT-2
          predicates:
            - Path=/service2/** # ?? gateway ??? /service2/**? ???? ?? eureka-client-2? ?????? ??
            - Method=GET

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    instance-id: gateway
