server:
  port: 8081

spring:
  application:
    name: eureka-client-1
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    instance-id: eureka-client-01