server:
  port: 8087

spring:
  application:
    name: delivery-service
  cloud:
    stream:
      bindings:
        decreaseProduct-in-0:
          destination: create-order
          content-type: application/json
          group: product-consumer
        increaseProductByUser-in-0:
          destination: cancel-order-by-user
          content-type: application/json
          group: product-consumer
        increaseProductBySystem-in-0:
          destination: cancel-order-by-system
          content-type: application/json
          group: product-consumer
        cancelOrderBySystem-out-0:
          destination: cancel-order-by-system
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
    function:
      definition: increaseProductByUser;increaseProductBySystem;decreaseProduct;
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}